[package]
name = "palace-testkit"
version.workspace = true
edition.workspace = true

[lib]
name = "palace_testkit"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
testcontainers = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
