[package]
name = "palace-backend"
version.workspace = true
edition.workspace = true
[lib]
name = "palace_backend"
path = "src/lib.rs"

[lints]
workspace = true

[features]
test-server = []

[dependencies]
palace-db = { workspace = true }
palace-domain = { workspace = true }
openidconnect = { workspace = true }
reqwest = { workspace = true }
axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
palace-logging = { workspace = true }
tokio = { workspace = true }
testcontainers = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true }
pretty_assertions = { workspace = true }
tower = { workspace = true }
http-body-util = { workspace = true }
